# S3 Endpoint Configuration
endpoint_url: 'https://eodata.dataspace.copernicus.eu'
endpoint_stac: 'https://stac.dataspace.copernicus.eu/v1/'
bucket_name: 'eodata'

# Dataset Configuration
dataset_version: 'data/marmara'
base_dir: '/home/ubuntu/mucilage_pipeline/mucilage-detection'
bands:
  - 'B02'
  - 'B03'
  - 'B04'
  - 'B08'
  - 'B12'

# Query Configuration
query:
  bbox:
    - 29.25
    - 40.75
    - 29.36
    - 40.7

  start_date: '2021-05-10'
  end_date: '2021-05-20'
  max_items: 1000
  max_cloud_cover: 30

# Download Configuration
download:
  sample_size: null  # Set to null for all samples
  resize: false
  resize_target: null
  l1c_resolution: 10
  l2a_resolution: 10
  max_attempts: 10
  retry_delay: 20