DATASET:
  version: "V4"
  base_dir: "home/ubuntu/mucilage_pipeline/mucilage-detection"
  bands : ['b01','b02', 'b03', 'b04', 'b05', 'b06', 'b07','b08','b8a', 'b11', 'b12']
  res : "r10m"

ENDPOINTS:
  url: "ttps://eodata.dataspace.copernicus.eu"
  stac: "https://stac.dataspace.copernicus.eu/v1/"
  bucket_name: "eodata"

MODEL:
  # model_name: "MIL_resnet18"
  # num_classes: 2
  # pretrained: True
  # log_features: False
  model_name: "Unet"
  encoder_name: "resnet18"
  encoder_weights: "imagenet"
  in_channel: 11
  num_classes: 2
  activation: None


TRAINING:
  batch_size: 16
  optim: "Adam"
  learning_rate: 0.0001
  scheduler: False
  scheduler_type: "ReduceLROnPlateau"
  factor: 0.5
  patience: 5
  num_epochs: 20
